---
title: "Figure 2"
output: 
  html_document: 
    toc: yes
author: 'Pietro Demela, Nicola Pirastu, Blagoje Soskic'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
knitr::opts_knit$set(root.dir =  "/project/aid_sharing/AID_sharing") #set up the project directory
```

## Libraries

```{r message=FALSE, warning=FALSE}
library(data.table)
library(ComplexHeatmap)
library(RColorBrewer)
library(qgraph)
```

## Load the dataset

```{r}
loci.table <- fread('outputs/rev_1/coloc_eqtl_mr/loci_definitions/final_locus_table.tsv', data.table = F) #take the original factor loci list
loci.table$final.locus=paste0(loci.table$Chr,":",loci.table$start,"-",loci.table$end,"_",loci.table$sub_locus)
```

## Figure 2B

Make the combination plot
```{r paged.print=FALSE}
#make the combination matrix of the loci
q <- make_comb_mat(list(f1=loci.table[which(loci.table$trait=='f1'),]$final.locus, f2=loci.table[which(loci.table$trait=='f2'),]$final.locus, f3=loci.table[which(loci.table$trait=='f3'),]$final.locus), mode = 'distinct')

#show the combination matrix 
q

plo2B<- UpSet(q, set_order = c("f1", "f2", "f3"), 
      comb_order = c(5,6,7,2,3,4,1),
      comb_col = c(brewer.pal(8, 'Set2')[c(7,6,6,6)],brewer.pal(12, 'Paired')[c(2,4,6)]),
      top_annotation = upset_top_annotation(q, add_numbers = TRUE, height = unit(6, "cm")),
      right_annotation = upset_right_annotation(q, add_numbers = TRUE, width = unit(5,'cm'),gp = gpar(fill = brewer.pal(5, 'Greys')[1])  ),
      row_title = "Factor", 
      column_title = "Intersection of all loci, colocalization")

#plot it
plo2B

#save it
pdf(width = 9, height = 5, file = 'outputs/rev_1/Figures/Fig_2/2B_upset_plot_final_loci_nicola.pdf')
plo2B
dev.off()

```

## Figure 2C

```{r paged.print=FALSE}

coloc_tab <-  fread('outputs/rev_1/coloc_eqtl_mr/loci_definitions/final_locus_table.tsv', data.table = F)
coloc_tab$final.locus=paste0(coloc_tab$Chr,":",coloc_tab$start,"-",coloc_tab$end,"_",coloc_tab$sub_locus)

#select locus 220 (16:11006011-11751015)
topl_220 <- coloc_tab[which(coloc_tab$pan.locus==220), c('trait', 'sub_locus', 'SNP', 'final.locus')]
topl_220

#remove the loci that are not colocalising between traits
topl_col <- topl_220[which(topl_220$final.locus %in% names(table(topl_220[,4])[which(table(topl_220[,4])!=1)])),]

topl_col

```
Plot the qgraph plot


```{r}

topl <- topl_col[,c(1,2)]
qgraph(topl, directed=F)

```

Search for the topSNP with the lower pvalue between the two co localizing loci

```{r paged.print=FALSE}
greg_220 <- loci.table[which(loci.table$pan.locus==220),]
topl$rsID <- rep(NA, nrow(topl))

for(i in topl$sub_locus){
      ll <- greg_220[which(greg_220$sub_locus==i), c('pJ', 'SNP')]
      topl[which(topl$sub_locus==i), ]$rsID <- rep(ll[order(ll$pJ),]$SNP[1], nrow(topl[which(topl$sub_locus==i), ]))
}


pdf('outputs/rev_1/Figures/Fig_2/2C_qgraph_locus_205_factors.pdf', width = 16, height = 16)
qgraph(topl[, c(1,3)], directed=F)
dev.off()

```

```{r}
sessionInfo()
```



