---
title: "Figure 4"
output: 
  html_document: 
    toc: yes
author: 'Pietro Demela, Nicola Pirastu, Blagoje Soskic'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
knitr::opts_knit$set(root.dir =  "/project/aid_sharing/AID_sharing") #set up the project directory
```

## Libraries

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(RColorBrewer)
library(VennDiagram)
library(stringr)
library(data.table)
library(ggplot2)
library(RColorBrewer)
library(dplyr)
```


```{r}
go <- readRDS('outputs/rev_1/10_pathways/go.RDS')
```

## Figure 4C

```{r message=TRUE, paged.print=FALSE}
#GO TERMS top 5 each


top_10_pathways <- unique(go$result[order(go$result$p_value, decreasing = F),][,'term_name'])[(1:10)]
kg <- go$result[which(go$result$term_name %in% top_10_pathways),c('query', 'p_value', 'term_name', 'intersection')]


colnames(kg) <- c( 'trait', 'padj','pathway', 'genes')


kg <- kg %>%
  arrange(-desc(padj)) %>%
  group_by(trait) %>%
  slice(1:5)

head(kg)

kg$pathway_f <- paste(kg$pathway, kg$trait, sep = '_')
kg$pathway_f <- factor(kg$pathway_f )


pdf('outputs/rev_1/Figures/Fig_4/4C_barplot_top5eachF.pdf', height = 10, width = 12)
 
ggplot(kg, aes(x = factor(pathway_f, levels = rev(pathway_f)), y = -log10(padj))) +
    coord_flip() +
    geom_bar(stat = 'identity') +
    theme(axis.line.x = element_line(),
          axis.line.y = element_line(),
          panel.grid = element_blank(),
          panel.background = element_blank(),
          legend.position = "off")

dev.off()

ggplot(kg, aes(x = factor(pathway_f, levels = rev(pathway_f)), y = -log10(padj))) +
    coord_flip() +
    geom_bar(stat = 'identity') +
    theme(axis.line.x = element_line(),
          axis.line.y = element_line(),
          panel.grid = element_blank(),
          panel.background = element_blank(),
          legend.position = "off")


```


## Figure 4D

```{r paged.print=FALSE}

#search the top 10 shared pathways and search the pvalues for all the factors for the top 10 pathways
shared_pathways_3 <- table(go$result$term_name)[which(table(go$result$term_name)==3)]
kg <- go$result[which(go$result$term_name %in% names(shared_pathways_3)),c('query', 'p_value', 'term_name', 'intersection')]
head(kg)

#order by pvalue
kg_or <- kg[order(kg$p_value),]

#pull the top 10 unique by pvalue
top_10_shared <- unique(kg$term_name)[1:10]
kg_10shared <- kg[which(kg$term_name %in% top_10_shared),]
dim(kg_10shared)


genes <- list()
to_merge <- list()

#loop for the pathways
for(i in 1:length(top_10_shared)){
  pp <- top_10_shared[i]
  
  #loop for the three factors
  for(k in 1:3){
    tt <- c('f1','f2', 'f3')[k]
    genes[[pp]][[tt]]<- str_split(kg[which(kg$term_name==pp & kg$query==tt),]$intersection, ',')[[1]]
    
  }
  
  #make a table for each of the pathways
  shared_2 <- unique(c(intersect(genes[[pp]]$f1, genes[[pp]]$f2), intersect(genes[[pp]]$f1, genes[[pp]]$f3), intersect(genes[[pp]]$f2, genes[[pp]]$f3)))
  shared_3 <- Reduce(intersect,genes[[pp]]) 
  all_genes <- unlist(genes[[pp]])
  
  tabp <- data.frame('gene'=unique(all_genes), 'sharing'=rep(NA, length(unique(all_genes))), 'pathway'=rep(pp, length(unique(all_genes))))
  tabp[which(tabp$gene%in% shared_2),]$sharing <- 'two'
  
  if( length(shared_3)!=0 ){tabp[which(tabp$gene%in% shared_3),]$sharing <-  'three'} #the intersection between three could be 0 and cause an error
  
  tabp[which(!tabp$gene%in% c(shared_3, shared_2)),]$sharing <- 'unique'
  to_merge[[pp]] <- tabp
  
  
}
final_t <- do.call(rbind, to_merge)

```
### Plot 

```{r}

Figure4D <- ggplot(final_t, aes(x=pathway, fill=sharing)) +
  geom_bar(stat='count',  color='black', position='fill')+
  scale_fill_manual(values = brewer.pal(8,'Set2')[c(2,1,8)]) +
  geom_text(aes(label = paste0("n=", ..count..)),position= 'fill',stat='count', color='Black')+
  labs(y = 'Number of genes', x = '')+
  theme_classic() + 
  theme(legend.position="bottom") + ggtitle('Top 10 GO Terms')


#show
Figure4D

#save
pdf('outputs/rev_1/Figures/Fig_4/4D_bar_plot_top10GOterm.pdf', width = 10, height = 7)
Figure4D
dev.off()
```

```{r}
sessionInfo()
```

