---
title: "S1_Supplementary_1"
author: "Pietro Demela, Nicola Pirastu, Blagoje Soskic"
date: "11/01/2023"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
knitr::opts_knit$set(root.dir =  "/project/aid_sharing/AID_sharing") #set up the project directory
```

### Libraries
```{r message=FALSE, warning=FALSE, paged.print=TRUE}
library(data.table)
library(GenomicSEM)
library(Matrix)
library(tidyr)
library(dplyr)
library(corrplot)
library(qgraph)
library(semPlot)
library(lavaan)
library(RColorBrewer)
library(gridExtra)
library(ggplot2)
library(ComplexHeatmap)

```

### Function for plotting sempaths

```{r message=TRUE, warning=TRUE}
library(semPlot)
library(lavaan)
semPlotModel_GSEM=function(gsem.object=GWISoutput , est.label="STD_All"){ 
  require(semPlot)
  object=gsem.object$results
  object$free=0
  numb=1:length(which(object$op!="~~"))
  object$free[which(object$op!="~~")]=numb
  varNames <- lavaanNames(object, type = "ov")
  factNames <- lavaanNames(object, type = "lv")
  factNames <- factNames[!factNames %in% varNames]
  n <- length(varNames)
  k <- length(factNames)
  if (is.null(object$label)) 
    object$label <- rep("", nrow(object))
  semModel <- new("semPlotModel")
  object$est <- object[,est.label]
  if (is.null(object$group)) 
    object$group <- ""
  semModel@Pars <- data.frame(label = object$label, lhs = ifelse(object$op == 
                                                                   "~" | object$op == "~1", object$rhs, object$lhs), edge = "--", 
                              rhs = ifelse(object$op == "~" | object$op == "~1", object$lhs, 
                                           object$rhs), est = object$est, std = NA, group = object$group, 
                              fixed = object$free==0, par = object$free, stringsAsFactors = FALSE)
  semModel@Pars$edge[object$op == "~~"] <- "<->"
  semModel@Pars$edge[object$op == "~*~"] <- "<->"
  semModel@Pars$edge[object$op == "~"] <- "~>"
  semModel@Pars$edge[object$op == "=~"] <- "->"
  semModel@Pars$edge[object$op == "~1"] <- "int"
  semModel@Pars$edge[grepl("\\|", object$op)] <- "|"
  semModel@Thresholds <- semModel@Pars[grepl("\\|", semModel@Pars$edge), 
                                       -(3:4)]
  semModel@Pars <- semModel@Pars[!object$op %in% c(":=", "<", 
                                                   ">", "==", "|", "<", ">"), ]
  semModel@Vars <- data.frame(name = c(varNames, factNames), 
                              manifest = c(varNames, factNames) %in% varNames, exogenous = NA, 
                              stringsAsFactors = FALSE)
  semModel@ObsCovs <- list()
  semModel@ImpCovs <- list()
  semModel@Computed <- FALSE
  semModel@Original <- list(object)
  return(semModel)
  
}

```

### Load ldsc output

```{r}
ldsc_ok <- readRDS('outputs/rev_1/02_munge_ldsc_sumstats/ldsc_output_rev1.RDS')
```


## S1

```{r}


library(qgraph)
pdf(file = 'outputs/rev_1/Figures/Supplementary_1/0_Network_complete.pdf', height = 9, width = 9 )
qgraph(ldsc_ok$S_Stand,threshold=0.40,layout="spring", diag=F, theme='gray')
dev.off()

#plot it
qgraph(ldsc_ok$S_Stand,threshold=0.40,layout="spring", diag=F, theme='gray')
```


## S2A

One Factor model 

```{r message=TRUE, warning=TRUE, paged.print=FALSE}
#estimate the model
one_f_model <-'F1 =~ NA*crohn + uc  + psc  +jia + sle + ra + t1d +asthma + derma 

F1 ~~ 1*F1

'
one_factor <-usermodel(ldsc_ok, estimation = "DWLS", model = one_f_model, CFIcalc = TRUE, std.lv = TRUE, imp_cov = FALSE)


one_factor

#plot the model
semPaths(semPlotModel_GSEM(one_factor), what = 'path' , 
         whatLabels= 'est',
         residuals = T, 
         sizeMan = 7, 
         sizeInt = 2,
         label.cex=1, 
         theme="colorblind", 
         rotation = 4, 
         layout = "tree2", 
         sizeLat = 7,
         edge.color = "black",
         edge.label.cex = 1,
         curve = 2,
         nodeLabels = c('CD', 'UC', 'PSC', 'JIA', 
                        'SLE', 'RA','T1D' ,'AST', 'ECZ' , 'F'), 
         label.cex = 1.5,
         height = 10, width = 16, 
         edge.label.position=0.5,
         asize=3,
         esize=1)
```

Save the output

```{r}
#save fit statistics
pdf('outputs/rev_1/Figures/Supplementary_1/1A_model_fit_one_factor.pdf', height = 16, width = 16)
grid.table(signif(one_factor$modelfit),2)
dev.off()

#save path
pdf('outputs/rev_1/Figures/Supplementary_1/1A_path_one_factor.pdf', height = 16, width = 16)
semPaths(semPlotModel_GSEM(one_factor), what = 'path' , 
         whatLabels= 'est',
         residuals = T, 
         sizeMan = 7, 
         sizeInt = 2,
         label.cex=1, 
         theme="colorblind", 
         rotation = 4, 
         layout = "tree2", 
         sizeLat = 7,
         edge.color = "black",
         edge.label.cex = 1,
         curve = 2,
         nodeLabels = c('CD', 'UC', 'PSC', 'JIA', 
                        'SLE', 'RA','T1D' ,'AST', 'ECZ' , 'F'), 
         label.cex = 1.5, 
         #color = list( lat=brewer.pal(12, 'Paired')[c(1,3,5)]),
         #groups=list(c("crohn","uc","psc"),c("jia","sle","ra_eu","t1d"), c( "asthma" ,"derma")),
         height = 10, width = 16, 
         edge.label.position=0.5,
         asize=3,
         esize=1)
dev.off()


```

## S2B

Two factor model

```{r paged.print=FALSE}

two_f_model <-'F1 =~ NA*crohn + uc  + psc  +jia + sle + ra + t1d 
F2 =~ NA*asthma + derma 

F1~~F2

F1 ~~ 1*F1
F2 ~~ 1*F2

derma~~a*derma
a>0.001
'

two_factor <-usermodel(ldsc_ok, estimation = "DWLS", model = two_f_model, CFIcalc = TRUE, std.lv = TRUE, imp_cov = FALSE)
two_factor



semPaths(semPlotModel_GSEM(two_factor), what = 'path' , 
         whatLabels= 'est',
         residuals = T, 
         sizeMan = 7, 
         sizeInt = 2,
         label.cex=1, 
         theme="colorblind", 
         rotation = 4, 
         layout = "tree2", 
         sizeLat = 7,
         edge.color = "black",
         edge.label.cex = 1,
         curve = 2,
         nodeLabels = c('CD', 'UC', 'PSC', 'JIA', 
                        'SLE', 'RA','T1D' ,'AST', 'ECZ' , 'F1', 'F2'), 
         label.cex = 1.5, 
         #color = list( lat=brewer.pal(12, 'Paired')[c(1,3,5)]),
         #groups=list(c("crohn","uc","psc"),c("jia","sle","ra_eu","t1d"), c( "asthma" ,"derma")),
         height = 10, width = 16, 
         edge.label.position=0.5,
         asize=3,
         esize=1)




```
Save

```{r}




pdf('outputs/rev_1/Figures/Supplementary_1/1B_path_two_factor_model.pdf', height = 16, width = 16)
semPaths(semPlotModel_GSEM(two_factor), what = 'path' , 
         whatLabels= 'est',
         residuals = T, 
         sizeMan = 7, 
         sizeInt = 2,
         label.cex=1, 
         theme="colorblind", 
         rotation = 4, 
         layout = "tree2", 
         sizeLat = 7,
         edge.color = "black",
         edge.label.cex = 1,
         curve = 2,
         nodeLabels = c('CD', 'UC', 'PSC', 'JIA', 
                        'SLE', 'RA','T1D' ,'AST', 'ECZ' , 'F1', 'F2'), 
         label.cex = 1.5, 
         #color = list( lat=brewer.pal(12, 'Paired')[c(1,3,5)]),
         #groups=list(c("crohn","uc","psc"),c("jia","sle","ra_eu","t1d"), c( "asthma" ,"derma")),
         height = 10, width = 16, 
         edge.label.position=0.5,
         asize=3,
         esize=1)
dev.off()

pdf('outputs/rev_1/Figures/Supplementary_1/1B_model_fit_two_factor_fit.pdf', height = 16, width = 16)
grid.table(signif(two_factor$modelfit,2))
dev.off()

```
## S2C

Three factor model

```{r paged.print=FALSE}
aid_model <-'F1 =~ NA*crohn + uc + psc  
F2 =~ NA*jia + sle + ra + t1d 
F3 =~ NA*asthma + derma 

F1~~F2
F1~~F3
F2~~F3

F1 ~~ 1*F1
F2 ~~ 1*F2
F3 ~~ 1*F3

derma~~a*derma
a>0.001
'

aid_factor <-usermodel(ldsc_ok, estimation = "DWLS", model = aid_model, CFIcalc = TRUE, std.lv = TRUE, imp_cov = FALSE)
aid_factor




semPaths(semPlotModel_GSEM(aid_factor), 
         what = 'path' , 
         whatLabels= 'est',
         residuals = T, 
         sizeMan = 8, 
         sizeInt = 10,
         label.cex=1, 
         theme="colorblind", 
         rotation = 4, 
         layout = "tree2", 
         sizeLat = 12,
         edge.color = "black",
         edge.label.cex = 1,
         curve = 2,
         nodeLabels = c('CD', 'UC', 'PSC', 'JIA', 
                        'SLE', 'RA','T1D' ,'AST', 'ECZ' , 'F1', 'F2', 'F3' ), 
         label.cex = 1.5, 
         color = list( lat=brewer.pal(12, 'Paired')[c(1,3,5)]),
         groups=list(c("crohn","uc","psc"),c("jia","sle","ra_eu","t1d"), c( "asthma" ,"derma")),
         height = 18, width = 18, 
         edge.label.position=0.5,
         asize=3,
         esize=1,
         
)


```

Save

```{r}


pdf('outputs/rev_1/Figures/Supplementary_1/1C_path_three_factor_model.pdf', height = 20, width = 18)
semPaths(semPlotModel_GSEM(aid_factor), 
         what = 'path' , 
         whatLabels= 'est',
         residuals = T, 
         sizeMan = 8, 
         sizeInt = 10,
         label.cex=1, 
         theme="colorblind", 
         rotation = 4, 
         layout = "tree2", 
         sizeLat = 12,
         edge.color = "black",
         edge.label.cex = 1,
         curve = 2,
         nodeLabels = c('CD', 'UC', 'PSC', 'JIA', 
                        'SLE', 'RA','T1D' ,'AST', 'ECZ' , 'F1', 'F2', 'F3' ), 
         label.cex = 1.5, 
         color = list( lat=brewer.pal(12, 'Paired')[c(1,3,5)]),
         groups=list(c("crohn","uc","psc"),c("jia","sle","ra_eu","t1d"), c( "asthma" ,"derma")),
         height = 18, width = 18, 
         edge.label.position=0.5,
         asize=3,
         esize=1,
         
)
dev.off()


pdf('outputs/rev_1/Figures/Supplementary_1/1C_model_fit_three_factor.pdf', height = 16, width = 16)
grid.table(signif(aid_factor$modelfit,2))
dev.off()

```
## S2D

Four factor model


```{r paged.print=FALSE}

aid_model_4 <-'F1 =~ NA*crohn + uc 
F2 =~ NA*jia + sle + ra + t1d 
F3 =~ NA*asthma + derma 
F4 =~ NA*psc + uc

F1~~F2
F1~~F3
F2~~F3
F1~~F4
F2~~F4
F3~~F4

F4 ~~ 1*F4
F1 ~~ 1*F1
F2 ~~ 1*F2
F3 ~~ 1*F3
derma~~a*derma
a>0.001
'

semPaths(semPlotModel_GSEM(aid_factor_4), what = 'path' , 
         whatLabels= 'est',
         residuals = T, 
         sizeMan = 7, 
         sizeInt = 2,
         label.cex=1, 
         theme="colorblind", 
         rotation = 4, 
         layout = "tree2", 
         sizeLat = 7,
         edge.color = "black",
         edge.label.cex = 1,
         curve = 2,
         #nodeLabels = c('CD', 'UC', 'PSC', 'JIA', 
                       # 'SLE', 'RA','T1D' ,'AST', 'ECZ' , 'F1', 'F2', 'F3', 'F4'), 
         height = 10, width = 16, 
         edge.label.position=0.5,
         asize=3,
         esize=1)


#run the model
aid_factor_4 <-usermodel(ldsc_ok, estimation = "DWLS", model = aid_model_4, CFIcalc = TRUE, std.lv = TRUE, imp_cov = FALSE)

aid_factor_4
```

Save


```{r}

pdf('outputs/rev_1/Figures/Supplementary_1/1D_path_four_factor_model.pdf', height = 20, width = 18)
semPaths(semPlotModel_GSEM(aid_factor_4), what = 'path' , 
         whatLabels= 'est',
         residuals = T, 
         sizeMan = 7, 
         sizeInt = 2,
         label.cex=1, 
         theme="colorblind", 
         rotation = 4, 
         layout = "tree2", 
         sizeLat = 7,
         edge.color = "black",
         edge.label.cex = 1,
         curve = 2,
         #nodeLabels = c('CD', 'UC', 'PSC', 'JIA', 
                       # 'SLE', 'RA','T1D' ,'AST', 'ECZ' , 'F1', 'F2', 'F3', 'F4'), 
         height = 10, width = 16, 
         edge.label.position=0.5,
         asize=3,
         esize=1)
dev.off()


pdf('outputs/rev_1/Figures/Supplementary_1/1D_model_fit_four_factor.pdf', height = 16, width = 16)
grid.table(signif(aid_factor_4$modelfit,2))
dev.off()

```


## Table of all models fit statistics

```{r}
one_factor$modelfit$n_factors <- '1'
two_factor$modelfit$n_factors <- '2'
aid_factor$modelfit$n_factors <- '3'
aid_factor_4$modelfit$n_factors <- '4'

fits <- do.call(rbind, list(one_factor$modelfit,
                            two_factor$modelfit,
                            aid_factor$modelfit,
                            aid_factor_4$modelfit)
                )

write.table(fits, 'outputs/rev_1/Figures/Supplementary_1/model_fit_table.txt', sep = '\t',quote = F)
```

## Tables of model results

```{r}
for(i in 1:4){
        
      ts <- list(one_factor$results, two_factor$results, aid_factor$results, aid_factor_4$results)[[i]]
      nam <- c('one', 'two', 'three', 'four')[i]
      fwrite(ts, paste0('outputs/rev_1/Figures/Supplementary_1/',nam, '_factor_model_result_table.txt'), sep = '\t', col.names = T, quote = F)
}

```

S7A

```{r paged.print=FALSE}
### load and assemble the table of MR results
mr_pqtl <- fread('outputs/rev_1/Supplementary_tables/12_Supplementary_table_pQTL_MR_results.csv', data.table = F)
head(mr_pqtl)
dim(mr_pqtl)

head(mr_pqtl)

#add effect direction column

mr_pqtl$effect <- ifelse(mr_pqtl$B>0, 1, -1)
head(mr_pqtl)

#select the columns needed to plot
plot_f <- mr_pqtl[, c(5,6,7,8)]
head(plot_f)
plot_f$plasma <- 'plasma'

plot_f$name <-paste(plot_f$GENE, plot_f$`LOCUS_NAME_(CHR:START_END)`) 


head(plot_f)

mat <-matrix(nrow =length(unique(plot_f$name)), ncol = length(unique(plot_f$plasma))) 
head(mat)

rownames(mat) <- unique(plot_f$name)


for(i in rownames(mat)){
  
 
    
    mat[i,1] <- ifelse(length(plot_f[which(plot_f$name==i),])!=0, paste0(plot_f[which(plot_f$name==i) , c( 'effect', 'TRAIT')], collapse = ''), NA)
    
  
}


names(table(mat))
colori <- ComplexHeatmap:::default_col(mat)
colori[names(table(mat))] <-  rep('white', 1)

for(i in 1:nrow(mat)){
  rownames(mat)[i] <- strsplit(rownames(mat)[i],' ')[[1]][1]
}

colnames(mat) <- 'Plasma'
dim(mat)
mat <-  as.data.frame(mat[order(rownames(mat)), ])



```

```{r fig.height=5, fig.width=2, paged.print=FALSE}

Heatmap(mat, 
        #column_title = "Genes and pathways KEGG",
        rect_gp = gpar(col = brewer.pal(5, 'Greys')[2], lwd = 0.25), 
        column_title_gp = gpar(fontsize = 10, fontface = "bold"),
        col=colori, 
        border=T,
        row_names_gp = gpar( fontsize=8),
        column_names_gp = gpar(fontsize=8),
        column_names_side = 'bottom',
        row_names_side = 'left',
        show_heatmap_legend = F,
        row_title = "Genes",
        na_col = 'white', 
        height = unit(10, 'cm'), width = 1, 
        
        
        
        cell_fun = function(j, i, x, y, width, height, fill) {
          if(!is.na(mat[i, j] )){
            
            if(mat[i, j]== '-1Faid' ){
              grid.points(x = x, y = y, pch = 25, size = unit(5, "mm"), gp = gpar(col = brewer.pal(6, 'Paired')[4], fill=brewer.pal(5, 'Paired')[4] ))
            }
            
            
            if(mat[i, j]== '1Faid' ){
              grid.points(x = x, y = y, pch = 24, size = unit(5, "mm"), gp = gpar(col = brewer.pal(5, 'Paired')[4], fill=brewer.pal(5, 'Paired')[4]))
            }
            
            if(mat[i, j]== '-1Falrg' ){
              grid.points(x = x, y = y, pch = 25, size = unit(5, "mm"), gp = gpar(col = brewer.pal(6, 'Paired')[6], fill=brewer.pal(6, 'Paired')[6]))
            }
            
            if(mat[i, j]== '1Falrg' ){
              grid.points(x = x, y = y, pch = 24, size = unit(5, "mm"), gp = gpar(col = brewer.pal(6, 'Paired')[6], fill=brewer.pal(6, 'Paired')[6]))
            }
            
            if(mat[i, j]== '1Fgut' ){
              grid.points(x = x, y = y, pch = 24, size = unit(5, "mm"), gp = gpar(col = brewer.pal(6, 'Paired')[2], fill=brewer.pal(6, 'Paired')[2]))
            }
            
            if(mat[i, j]== '-1Fgut' ){
              grid.points(x = x, y = y, pch = 25, size = unit(5, "mm"), gp = gpar(col = brewer.pal(6, 'Paired')[2], fill=brewer.pal(6, 'Paired')[2]))
            }
            
           
            
          }
          
        }
)
```



```{r}
pdf('outputs/rev_1/Figures/Supplementary_1/7A_pqtlMR.pdf', width = 2, height = 10)
Heatmap(mat, 
        #column_title = "Genes and pathways KEGG",
        rect_gp = gpar(col = brewer.pal(5, 'Greys')[2], lwd = 0.25), 
        column_title_gp = gpar(fontsize = 10, fontface = "bold"),
        col=colori, 
        border=T,
        row_names_gp = gpar( fontsize=8),
        column_names_gp = gpar(fontsize=8),
        column_names_side = 'bottom',
        row_names_side = 'left',
        show_heatmap_legend = F,
        row_title = "Genes",
        na_col = 'white', 
        height = unit(10, 'cm'), width = 1, 
        
        
        
        cell_fun = function(j, i, x, y, width, height, fill) {
          if(!is.na(mat[i, j] )){
            
            if(mat[i, j]== '-1Faid' ){
              grid.points(x = x, y = y, pch = 25, size = unit(5, "mm"), gp = gpar(col = brewer.pal(6, 'Paired')[4], fill=brewer.pal(5, 'Paired')[4] ))
            }
            
            
            if(mat[i, j]== '1Faid' ){
              grid.points(x = x, y = y, pch = 24, size = unit(5, "mm"), gp = gpar(col = brewer.pal(5, 'Paired')[4], fill=brewer.pal(5, 'Paired')[4]))
            }
            
            if(mat[i, j]== '-1Falrg' ){
              grid.points(x = x, y = y, pch = 25, size = unit(5, "mm"), gp = gpar(col = brewer.pal(6, 'Paired')[6], fill=brewer.pal(6, 'Paired')[6]))
            }
            
            if(mat[i, j]== '1Falrg' ){
              grid.points(x = x, y = y, pch = 24, size = unit(5, "mm"), gp = gpar(col = brewer.pal(6, 'Paired')[6], fill=brewer.pal(6, 'Paired')[6]))
            }
            
            if(mat[i, j]== '1Fgut' ){
              grid.points(x = x, y = y, pch = 24, size = unit(5, "mm"), gp = gpar(col = brewer.pal(6, 'Paired')[2], fill=brewer.pal(6, 'Paired')[2]))
            }
            
            if(mat[i, j]== '-1Fgut' ){
              grid.points(x = x, y = y, pch = 25, size = unit(5, "mm"), gp = gpar(col = brewer.pal(6, 'Paired')[2], fill=brewer.pal(6, 'Paired')[2]))
            }
            
           
            
          }
          
        }
)
```









